//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.02 at 07:07:14 PM EET 
//


package ua.yuriih.lab2.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Chars complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Chars">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="paid" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="hasEmail" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="hasNews" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="hasArchives" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="poll">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="anonymous"/>
 *               &lt;enumeration value="authorized"/>
 *               &lt;enumeration value="no"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Chars", propOrder = {
    "paid",
    "hasEmail",
    "hasNews",
    "hasArchives",
    "poll"
})
public class Chars {

    protected boolean paid;
    protected boolean hasEmail;
    protected boolean hasNews;
    protected boolean hasArchives;
    @XmlElement(required = true)
    protected String poll;

    /**
     * Gets the value of the paid property.
     * 
     */
    public boolean isPaid() {
        return paid;
    }

    /**
     * Sets the value of the paid property.
     * 
     */
    public void setPaid(boolean value) {
        this.paid = value;
    }

    /**
     * Gets the value of the hasEmail property.
     * 
     */
    public boolean isHasEmail() {
        return hasEmail;
    }

    /**
     * Sets the value of the hasEmail property.
     * 
     */
    public void setHasEmail(boolean value) {
        this.hasEmail = value;
    }

    /**
     * Gets the value of the hasNews property.
     * 
     */
    public boolean isHasNews() {
        return hasNews;
    }

    /**
     * Sets the value of the hasNews property.
     * 
     */
    public void setHasNews(boolean value) {
        this.hasNews = value;
    }

    /**
     * Gets the value of the hasArchives property.
     * 
     */
    public boolean isHasArchives() {
        return hasArchives;
    }

    /**
     * Sets the value of the hasArchives property.
     * 
     */
    public void setHasArchives(boolean value) {
        this.hasArchives = value;
    }

    /**
     * Gets the value of the poll property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoll() {
        return poll;
    }

    /**
     * Sets the value of the poll property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoll(String value) {
        this.poll = value;
    }

}
